import { Roboto } from "next/font/google";
import "./globals.css";
import { Container } from "@mui/material";
import Menu from "./components/NavBar";
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });
import "./globals.css";

export const metadata = {
	title: "App Notes Dev",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Menu></Menu>
				<Container>{children}</Container>
			</body>
		</html>
	);
}
